/*! *****************************************************************************
  mmm-jast
  Version 2.9.5

  A minimalistic stock ticker based on Yahoo's finance API for the MagicMirror² platform.
  Please submit bugs at https://github.com/jalibu/MMM-Jast/issues

  (c) Jan.Litzenburger@gmail.com
  Licence: MIT

  This file is auto-generated. Do not edit.
***************************************************************************** */

"use strict";var e=require("node_helper"),r=require("logger"),t=require("yahoo-finance2");function n(e){return e&&e.__esModule?e:{default:e}}function s(e){if(e&&e.__esModule)return e;var r=Object.create(null);return e&&Object.keys(e).forEach(function(t){if("default"!==t){var n=Object.getOwnPropertyDescriptor(e,t);Object.defineProperty(r,t,n.get?n:{enumerable:!0,get:function(){return e[t]}})}}),r.default=e,Object.freeze(r)}var o=s(e),a=s(r),i=n(t);function c(e,r,t,n){return new(t||(t=Promise))(function(s,o){function a(e){try{c(n.next(e))}catch(e){o(e)}}function i(e){try{c(n.throw(e))}catch(e){o(e)}}function c(e){var r;e.done?s(e.value):(r=e.value,r instanceof t?r:new t(function(e){e(r)})).then(a,i)}c((n=n.apply(e,r||[])).next())})}"function"==typeof SuppressedError&&SuppressedError;class u{static requestStocks(e){return c(this,void 0,void 0,function*(){var r;const t=new i.default,n=[],s=[];for(const r of e.stocks)s.push(t.quoteSummary(r.symbol,{modules:["price"]}));const o=yield Promise.all(s.map(e=>e.catch(e=>e)));for(const[t,s]of o.entries())if(s instanceof Error)a.warn(`API request for ${e.stocks[t].symbol} failed:`,s.message);else if(s.price){const o={symbol:e.stocks[t].symbol,name:e.stocks[t].name,quantity:e.stocks[t].quantity,hidden:e.stocks[t].hidden,purchasePrice:e.stocks[t].purchasePrice};if("GBp"===s.price.currency&&(s.price.regularMarketPrice/=100,s.price.regularMarketChange/=100,s.price.currency="GBP"),e.maxChangeAge>0){const t=(new Date).getTime()-e.maxChangeAge;try{t>Date.parse(s.price.regularMarketTime)&&(s.price.regularMarketPreviousClose=null===(r=s.price)||void 0===r?void 0:r.regularMarketPrice,s.price.regularMarketChange=0,s.price.regularMarketChangePercent=0)}catch(e){a.warn("Could not parse lastChange date",e)}}n.push({price:s.price,meta:o})}else a.warn(`Response for ${e.stocks[t].symbol} does not satisfy expected payload.`);return n})}}const l=["regularMarketChange","regularMarketChangePercent","regularMarketPrice","currency","longName","regularMarketPreviousClose"];module.exports=o.create({start(){a.log(`${this.name} helper method started...`)},socketNotificationReceived(e,r){return c(this,void 0,void 0,function*(){if(e.includes("JAST_STOCKS_REQUEST")){const t=e.substring(20);let n=yield u.requestStocks(r);n=n.filter(e=>l.every(r=>!!Object.prototype.hasOwnProperty.call(e.price,r)||(a.warn(`Skipped symbol '${e.meta.symbol}' as it's response did not have required property '${r}'. This is usually the case when a symbol is misspelled`),!1)));const s={lastUpdate:Date.now(),stocks:n};this.sendSocketNotification(`JAST_STOCKS_RESPONSE-${t}`,s)}else a.warn(`${e} is invalid notification`)})}});
